# Generated by Django 3.2 on 2022-05-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_score_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='submitted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
